lints.workspace = true

[package]
name = "uniffi-bindgen-swift"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
uniffi = { workspace = true, features = ["cli"] }

[[bin]]
name = "uniffi-bindgen-swift"
path = "src/main.rs"
